# Generated by Django 3.2.6 on 2021-08-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departments',
            new_name='department',
        ),
    ]
