# Generated by Django 3.2.6 on 2021-09-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exp_delivery_date',
            field=models.DateField(null=True),
        ),
    ]
