# Generated by Django 3.2.6 on 2021-08-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
