# Generated by Django 3.2.6 on 2021-09-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=60, unique=True)),
                ('brand_name', models.CharField(max_length=60)),
                ('price', models.PositiveIntegerField()),
                ('copies', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('intransit', 'intransit'), ('cancelled', 'cancelled'), ('ordered', 'ordered')], default='ordered', max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('exp_delivery_date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.mobile')),
            ],
        ),
    ]
